name: raggy

include:
  - storage.compose.yaml
  - observability.compose.yaml
  - infrastructure.compose.yaml

services:
  auth-service:
    build:
      context: ../
      dockerfile: services/simple-auth-service/dev.Dockerfile
    env_file:
      - ../services/simple-auth-service/.env.example
    environment:
      ENV: development
      DB_CONNECTION_STRING: postgres://postgres:auth_password@auth-db:5432/postgres
      ARGON2_PASSWORD_PEPPER: raggy-secret-pepper-2026

      TELEMETRY_COLLECTOR_ENDPOINT: tempo:4317
    volumes:
      - "../:/app"
      - auth_service_pkg:/go/pkg/mod
    labels:
      - project.group=services
    depends_on:
      - auth-db

  dashboard-service:
    build:
      context: ../
      dockerfile: services/dashboard/dev.Dockerfile
    environment:
      ENV: development
      DB_CONNECTION_STRING: postgres://postgres:dashboard_password@dashboard-db:5432/postgres
      KAFKA_SEED_BROKERS: "kafka:9092"

      S3_ENDPOINT: "http://s3.localhost"
      S3_ACCESS_KEY_ID: admin
      S3_SECRET_ACCESS_KEY: miniopassword

      ACCESS_TOKEN_PUBLIC_KEY: 0qw/WOYvsmc3TJKKebk3vawfmo8aKGM6lpFchb6XviI=

      TELEMETRY_COLLECTOR_ENDPOINT: tempo:4317

    volumes:
      - "../:/app"
      - dashboard_service_pkg:/go/pkg/mod
    labels:
      - project.group=services
    depends_on:
      - dashboard-db

  ingestion-worker:
    build:
      context: ../
      dockerfile: services/ingestion-worker/dev.Dockerfile
    environment:
      KAFKA_SEED_BROKERS: "kafka:9092"

      S3_ENDPOINT: "http://s3.localhost"
      S3_ACCESS_KEY_ID: admin
      S3_SECRET_ACCESS_KEY: miniopassword

      TELEMETRY_COLLECTOR_ENDPOINT: tempo:4317
    volumes:
      - "../:/app"
      - ingestion_worker_pkg:/go/pkg/mod
    labels:
      - project.group=services

  rag-service:
    build:
      context: ../
      dockerfile: services/rag/dev.Dockerfile
    env_file:
      - ../services/rag/.env
    environment:
      ENV: development
      DB_CONNECTION_STRING: postgres://postgres:rag_password@rag-db:5432/postgres
      ACCESS_TOKEN_PUBLIC_KEY: 0qw/WOYvsmc3TJKKebk3vawfmo8aKGM6lpFchb6XviI=

      KAFKA_SEED_BROKERS: "kafka:9092"

      TELEMETRY_COLLECTOR_ENDPOINT: tempo:4317
    volumes:
      - "../:/app"
      - rag_service_pkg:/go/pkg/mod
    labels:
      - project.group=services
    depends_on:
      - rag-db

  frontend:
    build:
      context: ../frontend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: "development"
      PORT: 80
    volumes:
      - ../frontend:/app
      - frontend_pkg:/app/node_modules

volumes:

  auth_service_pkg:
  dashboard_service_pkg:
  ingestion_worker_pkg:
  rag_service_pkg:
  frontend_pkg:
