name: raggy

services:
  proxy:
    image: nginx:alpine
    container_name: raggy-proxy
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
    networks:
      default:
        aliases:
          - s3.localhost

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1

      KAFKA_KRAFT_MODE: "true"

      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      # Listeners
      # 9092: Internal/External traffic
      # 9093: Controller/Raft traffic
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      # workarounds for single node 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-init:
    image: apache/kafka:latest
    container_name: raggy-kafka-init
    entrypoint: [ "/bin/bash", "/usr/local/bin/init-kafka.sh" ]
    restart: "no"
    volumes:
      - ./kafka-init.sh:/usr/local/bin/init-kafka.sh
    depends_on:
      - kafka

  kafka-ui:
    container_name: kafka-ui
    image: tchiotludo/akhq
    ports:
      - "9080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            my-local-cluster:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka

  s3:
    image: minio/minio
    container_name: raggy-s3
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Web Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: miniopassword

      MINIO_NOTIFY_KAFKA_ENABLE_primary: on
      MINIO_NOTIFY_KAFKA_BROKERS_primary: kafka:9092
      MINIO_NOTIFY_KAFKA_TOPIC_primary: s3-events
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  s3-init:
    image: minio/mc
    container_name: raggy-s3-init
    depends_on:
      - s3
    volumes:
      - ./s3-init.sh:/s3-init.sh
    entrypoint: [ "/bin/sh", "/s3-init.sh" ]

  auth-db:
    image: postgres:18-alpine
    container_name: raggy-auth-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql

  auth-service:
    build:
      context: ../
      dockerfile: services/simple-auth-service/dev.Dockerfile
    container_name: raggy-auth-service
    depends_on:
      - auth-db
    environment:
      ENV: development
      DB_CONNECTION_STRING: postgres://postgres:auth_password@auth-db:5432/postgres
    env_file:
      - ../services/simple-auth-service/.env.example
    volumes:
      - "../:/app"
      - auth-service-pkg:/go/pkg/mod

  dashboard-db:
    image: postgres:18-alpine
    container_name: raggy-dash-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dashboard_password
    ports:
      - "5433:5432"
    volumes:
      - dashboard-data:/var/lib/postgresql

  dashboard-service:
    build:
      context: ../
      dockerfile: services/dashboard/dev.Dockerfile
    container_name: raggy-dash-service
    depends_on:
      - auth-db
    environment:
      ENV: development
      DB_CONNECTION_STRING: postgres://postgres:dashboard_password@dashboard-db:5432/postgres

      KAFKA_SEED_BROKERS: "kafka:9092"

      S3_ENDPOINT: "http://s3.localhost"
      S3_ACCESS_KEY_ID: admin
      S3_SECRET_ACCESS_KEY: miniopassword

      ACCESS_TOKEN_PUBLIC_KEY: 0qw/WOYvsmc3TJKKebk3vawfmo8aKGM6lpFchb6XviI=
    volumes:
      - "../:/app"
      - dashboard-service-pkg:/go/pkg/mod

  ingestion-worker:
    build:
      context: ../
      dockerfile: services/ingestion-worker/dev.Dockerfile
    container_name: raggy-ingestion-worker
    environment:
      KAFKA_SEED_BROKERS: "kafka:9092"

      S3_ENDPOINT: "http://s3.localhost"
      S3_ACCESS_KEY_ID: admin
      S3_SECRET_ACCESS_KEY: miniopassword

    volumes:
      - "../:/app"
      - ingestion-worker-pkg:/go/pkg/mod

  frontend:
    build:
      context: ../frontend
      dockerfile: dev.Dockerfile
    container_name: raggy-frontend
    environment:
      NODE_ENV: "development"
      PORT: 80
    volumes:
      - ../frontend:/app
      - frontend-pkg:/app/node_modules

volumes:
  minio-data:

  auth-service-pkg:
  auth-data:

  dashboard-service-pkg:
  dashboard-data:

  ingestion-worker-pkg:

  frontend-pkg:
