name: raggy

services:
  proxy:
    image: nginx:alpine
    container_name: raggy-proxy
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service

  s3:
    image: minio/minio
    container_name: raggy-s3
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Web Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  s3-init:
    image: minio/mc
    container_name: raggy-s3-init
    depends_on:
      - s3
    volumes:
      - ./s3-init.sh:/s3-init.sh
    entrypoint: [ "/bin/sh", "/s3-init.sh" ]

  auth-database:
    image: postgres:18-alpine
    container_name: raggy-auth-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - auth-database:/var/lib/postgresql

  auth-service:
    build:
      context: ../
      dockerfile: services/simple-auth-service/dev.Dockerfile
    container_name: raggy-auth-service
    depends_on:
      - auth-database
    environment:
      ENV: development
      DB_CONNECTION_STRING: postgres://postgres:auth_password@auth-database:5432/postgres
    env_file:
      - ../services/simple-auth-service/.env.example
    volumes:
      - "../:/app"
      - auth-service-packages:/go/pkg/mod

volumes:
  auth-service-packages:
  auth-database:
  minio-data:
